spring:
  application:
    name: kafka-consumer
  cloud:
    function:
      definition: processRiderLocation; processRiderStatus
    stream:
      function:
        definition: processRiderLocation; processRiderStatus
      bindings:
        processRiderLocation-in-0:
          destination: my-topic
#          group: rider-location-group
        processRiderStatus-in-0:
          destination: my-new-topic
#          group: rider-status-group
      kafka:
        binder:
          brokers: localhost:9092
server:
  port: 8081


#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092