#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: user-service
#              uri: lb://USER-SERVICE
#              predicates:
#                - Path=/api/user/**
#            - id: product-service
#              uri: lb://PRODUCT-SERVICE
#              predicates:
#                - Path=/api/product/**
#            - id: order-service
#              uri: lb://ORDER-SERVICE
#              predicates:
#                - Path=/api/order/**,/api/cart/**
#            - id: eureka-service
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/main
#              filters:
#                - RewritePath=/eureka/main,/
#            - id: eureka-server-static
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/**

  server:
    port: 8080

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    tracing:
      sampling:
        propability: 1.0

  #eureka:
  #  client:
  #    serviceUrl:
  #        defaultZone: http://localhost:8761/eureka/
  #    register-with-eureka: true
  #    fetch-registry: true