spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    datasource: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  #  security:
  #    enabled: false
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      propability: 1.0
app:
  message: "Hello Order service"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# logging.level.root: info
# logging.level.com.ecommerce.user: debug
# save the logs in a file
logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
# resilience4j circuit breaker working
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based
  retry:
    instances:
      retryBreaker:
        maxAttempts: 3
        waitDuration: 500ms

# ###############################################33
# - resilience4j circuit breaker for above spring boot 4 above
#resilience4j.circuitbreaker:
#    configs:
#      default:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        waitDurationInOpenState: 10s
#        failureRateThreshold: 50
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        slidingWindowType: count_based
#    instances:
#      productService:
#        baseConfig: default